### ISSUE TITLE
Starting tunnel in import script doesn't work in Python 2.7

### ISSUE THREAD

**Issue by fouwst** [pahaz/sshtunnel#152]
I have a simple script (foo.py) that imports another script. The contents of the script are simply:

`import bar`

In the import script, sshtunnel is imported, and a tunnel is opened:

```
from sshtunnel import SSHTunnelForwarder

server = SSHTunnelForwarder(
	('ssh-tunnel.xxx.com', 22),
	ssh_username='xxx',
	ssh_private_key='/Users/xxx/.ssh/id_rsa',
	ssh_private_key_password='xxx',
	remote_bind_address=('127.0.0.1', 5433),
        local_bind_address=('0.0.0.0', 52704)
)

server.start()
print(server.is_active)
server.stop()
```
In python 3.7.3, the tunnel opens successfully, the is_active boolean prints True, and the tunnel closes.

In python 2.7.16, the tunnel is never successfully opened and the operation hangs forever.

If I move the contents of the import script into the main script, the connection is successful in both cases, but when the logic resides in an import script, it does not work in 2.7.

**Comment by fernandezcuesta** [comment]
Hi, I could reproduce your issue and honestly there's nothing we can do, since all my findings point to paramiko.
You can still set a non-blocking transport with `sshtunnel.SSH_TIMEOUT = 1.0` (or any other value in seconds) and daemonising the transports with:

server.daemon_forward_servers = True
server.daemon_transport = True

or just use helper method `open_tunnel(..., block_on_close=False)`

**Comment by SamuelePolimi** [comment]
I experience a similar issue. In python 3.6 the same script run without errors, while in python 2.7. output an error "AttributeError: 'module' object has no attribute 'ECDSAKey'" (at line 1218 of sshtunnel.py).

I don't know how to solve the problem. Unfortunately I need the client to be in python 2.7.

**Comment by pahaz** [comment]
Could you please test it in on the latest version with logleve=1. And open a new issue if you still have any problem
